version: "3.5"

services:
  db:
    container_name: db_library
    image: postgres    
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    networks:
      - library-net

networks:
  library-net:
    name: library-net
    driver: bridge
