name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: docker-compose up --build -d
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rodando os Testes
        run: docker-compose run web sh -c "python manage.py migrate && python manage.py test"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rodando o Lint
        run: docker-compose run web sh -c "pylint manage.py --disable=C"
  cd-front:
    name: CD-Front
    runs-on: ubuntu-latest
    # needs: 
    #   - lint      
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./library_front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library_front:latest
  cd-back:
    name: CD-Back
    runs-on: ubuntu-latest
    # needs: 
    #   - lint      
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./library_back/Dockerfile          
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library_back:latest
    
